// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OU.TaskandTimeTrackingSystem.TimeTracking.Api.DataAccess.Context;

#nullable disable

namespace OU.TaskandTimeTrackingSystem.TimeTracking.Api.Migrations
{
    [DbContext(typeof(TimeTrackingContext))]
    [Migration("20250629190459_mig_2")]
    partial class mig_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.ActivityLogs.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.BreakPeriod.BreakPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TimeEntryId")
                        .HasMaxLength(16)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimeEntryId");

                    b.ToTable("BreakPeriods");
                });

            modelBuilder.Entity("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.ManuelTimeAdjustments.ManuelTimeAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("RelatedTimeEntryId")
                        .HasMaxLength(16)
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(16)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ManuelTimeAdjustments");
                });

            modelBuilder.Entity("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.Reminders.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ReminderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TimeEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimeEntryId")
                        .IsUnique();

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.TimeEntry.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskId")
                        .HasMaxLength(16)
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(16)
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkSessionId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.WorkSessions.WorkSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedTasks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<long>("TotalTrackedTime")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkSessions");
                });

            modelBuilder.Entity("TagTimeEntry", b =>
                {
                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeEntriesId")
                        .HasColumnType("uuid");

                    b.HasKey("TagsId", "TimeEntriesId");

                    b.HasIndex("TimeEntriesId");

                    b.ToTable("TagTimeEntry");
                });

            modelBuilder.Entity("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.BreakPeriod.BreakPeriod", b =>
                {
                    b.HasOne("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.TimeEntry.TimeEntry", "TimeEntry")
                        .WithMany("BreakPeriods")
                        .HasForeignKey("TimeEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeEntry");
                });

            modelBuilder.Entity("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.Reminders.Reminder", b =>
                {
                    b.HasOne("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.TimeEntry.TimeEntry", "TimeEntry")
                        .WithOne()
                        .HasForeignKey("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.Reminders.Reminder", "TimeEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeEntry");
                });

            modelBuilder.Entity("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.TimeEntry.TimeEntry", b =>
                {
                    b.HasOne("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.WorkSessions.WorkSession", null)
                        .WithMany("TimeEntries")
                        .HasForeignKey("WorkSessionId");
                });

            modelBuilder.Entity("TagTimeEntry", b =>
                {
                    b.HasOne("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.Tags.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.TimeEntry.TimeEntry", null)
                        .WithMany()
                        .HasForeignKey("TimeEntriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.TimeEntry.TimeEntry", b =>
                {
                    b.Navigation("BreakPeriods");
                });

            modelBuilder.Entity("OU.TaskandTimeTrackingSystem.TimeTracking.Api.Features.WorkSessions.WorkSession", b =>
                {
                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
